//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _41PP_TRifonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public int IDBook { get; set; }
        public int IDReader { get; set; }
        public int IDLibrary { get; set; }
        public int countBooks { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Libraries Libraries { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
