//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _41PP_TRifonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int ReaderID { get; set; }
        public int FromWhere { get; set; }
        public int ToWhere { get; set; }
        public int BookID { get; set; }
        public int countBooks { get; set; }
        public int look { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Libraries Libraries { get; set; }
        public virtual Libraries Libraries1 { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
