//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _41PP_TRifonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksAndGanres
    {
        public int BookAndGanreID { get; set; }
        public int IDCatalog { get; set; }
        public int IDUnderTheDirectory { get; set; }
        public Nullable<int> IDGanre { get; set; }
        public int IDBook { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Catalogs Catalogs { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual SubDirectory SubDirectory { get; set; }
    }
}
