//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _41PP_TRifonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        public int LibraryCardNumber { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Otshestvo { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string TelefonNumber { get; set; }
        public string Address { get; set; }
        public string PlaceOfStudy { get; set; }
        public string PlaceOfWork { get; set; }
        public int GenderID { get; set; }
        public string Email { get; set; }
        public Nullable<int> InformationAboutParentsID { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime ReissuanceDate { get; set; }
        public int IDLibrary { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual InformationAboutParents InformationAboutParents { get; set; }
        public virtual Libraries Libraries { get; set; }
    }
}
